"use client";

import { DataTable } from '@/components/ui/e-data-table';
import type { DataTableRow } from '@/components/ui/e-data-table';

const rows: DataTableRow[] = [
  // Page 1 — all 4 statuses visible
  {
    avatarSrc: "https://i.pravatar.cc/40?img=3",
    header: "Marco Odermatt",
    id: "1",
    limit: 20,
    reviewer: "Helmut Krug",
    sectionType: "Giant Slalom",
    status: "in-process",
    target: 24,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=5",
    header: "Mikaela Shiffrin",
    id: "2",
    limit: 26,
    reviewer: "Mike Day",
    sectionType: "Slalom",
    status: "done",
    target: 28,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=10",
    header: "Sofia Goggia",
    id: "3",
    limit: 12,
    reviewer: "M. Blardone",
    sectionType: "Downhill",
    status: "cancelled",
    target: 18,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=12",
    header: "Alexis Pinturault",
    id: "4",
    limit: 18,
    reviewer: null,
    sectionType: "All-round",
    status: "pending",
    target: 22,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=9",
    header: "Lara Gut-Behrami",
    id: "5",
    limit: 17,
    reviewer: "M. Blardone",
    sectionType: "Super-G",
    status: "done",
    target: 20,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=15",
    header: "Henrik Kristoffersen",
    id: "6",
    limit: 22,
    reviewer: "Helmut Krug",
    sectionType: "Slalom",
    status: "in-process",
    target: 26,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=11",
    header: "Petra Vlhová",
    id: "7",
    limit: 20,
    reviewer: null,
    sectionType: "Slalom",
    status: "pending",
    target: 24,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=8",
    header: "Corinne Suter",
    id: "8",
    limit: 14,
    reviewer: "M. Blardone",
    sectionType: "Downhill",
    status: "done",
    target: 16,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=20",
    header: "Matthias Mayer",
    id: "9",
    limit: 10,
    reviewer: "Christian Pravda",
    sectionType: "Super-G",
    status: "cancelled",
    target: 14,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=13",
    header: "Wendy Holdener",
    id: "10",
    limit: 20,
    reviewer: null,
    sectionType: "All-round",
    status: "done",
    target: 22,
  },
  // Page 2
  {
    avatarSrc: "https://i.pravatar.cc/40?img=17",
    header: "Loïc Meillard",
    id: "11",
    limit: 16,
    reviewer: "Helmut Krug",
    sectionType: "Giant Slalom",
    status: "in-process",
    target: 20,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=16",
    header: "Federica Brignone",
    id: "12",
    limit: 22,
    reviewer: "M. Blardone",
    sectionType: "All-round",
    status: "done",
    target: 24,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=22",
    header: "Vincent Kriechmayr",
    id: "13",
    limit: 14,
    reviewer: null,
    sectionType: "Downhill",
    status: "pending",
    target: 18,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=19",
    header: "Ragnhild Mowinckel",
    id: "14",
    limit: 18,
    reviewer: "Mike Day",
    sectionType: "Giant Slalom",
    status: "done",
    target: 20,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=25",
    header: "Clément Noël",
    id: "15",
    limit: 24,
    reviewer: "Helmut Krug",
    sectionType: "Slalom",
    status: "in-process",
    target: 26,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=18",
    header: "Marta Bassino",
    id: "16",
    limit: 20,
    reviewer: "M. Blardone",
    sectionType: "Giant Slalom",
    status: "done",
    target: 22,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=30",
    header: "Beat Feuz",
    id: "17",
    limit: 12,
    reviewer: "Christian Pravda",
    sectionType: "Downhill",
    status: "cancelled",
    target: 16,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=21",
    header: "Tessa Worley",
    id: "18",
    limit: 16,
    reviewer: null,
    sectionType: "Giant Slalom",
    status: "pending",
    target: 20,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=33",
    header: "Zan Kranjec",
    id: "19",
    limit: 18,
    reviewer: "Helmut Krug",
    sectionType: "Giant Slalom",
    status: "done",
    target: 22,
  },
  {
    avatarSrc: "https://i.pravatar.cc/40?img=23",
    header: "Katharina Liensberger",
    id: "20",
    limit: 20,
    reviewer: null,
    sectionType: "Slalom",
    status: "in-process",
    target: 24,
  },
];

export function DataTableDemo() {
  return <DataTable rows={rows} />;
}
